### PR TITLE
Updated Jetty and Javalib core to newest versions

### LINKED ISSUE #30: Building with Java 1.8 throws javadoc creation error
With Java 1.8, building using command :

```
mvn clean package assembly:single
```

throws following exceptions and fails:

``` Java
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:205)
[ERROR] at com.sun.tools.javadoc.Main.execute(Main.java:64)
[ERROR] at com.sun.tools.javadoc.Main.main(Main.java:54)
[ERROR] javadoc: error - java.lang.IllegalArgumentException
[ERROR]
[ERROR] Command line was: <somepath>\Java\jdk1.8.0_60\jre\..\bin\javadoc.exe -J-Dhttp.proxySet=true -J-Dhttp.proxyHost=foo.com -J-Dht
tp.proxyPort=nn "-J-Dhttp.nonProxyHosts=\"localhost|*.foo.com\"" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '<somepath>\jrobotremoteserver\target\apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Solution:
[Reference: ](http://stackoverflow.com/questions/24615547/cant-build-hadoop-2-4-1-with-java8)

Need to build using following command:

```
mvn  clean package assembly:single -Dmaven.javadoc.skip=true
```

### LINKED ISSUE #34: jrobotremoteserver not working with Selenium-server
I'll try to start remote server with following dependencies:

```
dependencies {
    compile 'log4j:log4j:1.2.17'
    runtime 'com.github.hi-fi:remotesikulilibrary:0.0.4.3'
    runtime('com.github.markusbernhardt:robotframework-selenium2library-java:1.4.0.8')
}
```

remotesikulilibrary utilizes jrobotremoteserver package.

At start with ".\gradlew.bat runRemoteServer" it thows exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError:org/eclipse/jetty/util/component/AggregateLifeCycle
```

Error is probably version conflict, as selenium-server uses (repacked) jetty 9.2.13.v20150730, and jrobotremoteserver relies on 7.6 series of jetty.

In test set there's both Sikuli and Selenium tests, which is why both are at dependencies.

### LINKED ISSUE #44: Upgrade project to Jetty 9.x
Hi @ombre42 

My organisation uses this project to invoke robot server. However when we upgraded to jetty 9.x from 7.x we found that the server doesn't start. This is because jetty v9.x doesn't include the `SelectChannelConnector`class as they have moved away from HTTP/1.x

I feel that `SelectChannelConnector`can be replaced by `ServerConnector` in `RemoteServer.java` and other particular location with minor refactor. I am also working on this after the holiday, but do you think this is feasible and we can package this into a release and ship to maven?

Thank you

### PR DESCRIPTION
**Pull request by Hi-Fi**
API according Robot framework documentation

Java requirement to Java 8

Fixes #30 
Fixes #34 
Fixes #44

### CODE REVIEW

**Comment by Hi-Fi** [comment]
@ombre42 Any comments? I'd like to get version which is working with JavalibCore 2.x published, and same time there has been also some bugs that I have encountered. This is just base for those other fixes, as I don't see reason of keeping dependency versions too old.

**Comment by Hi-Fi** [comment]
Done separately, released with 4.0.0.
